# Generated by Django 4.0 on 2024-03-02 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='users_with_access',
            field=models.ManyToManyField(blank=True, related_name='products_with_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
